### ISSUE TITLE
Could not detect Servos

### ISSUE THREAD

**Issue by hokster7** [vanadiumlabs/pypose#11]
I've connected exactly one Bioloid Dynamixel MX-28 servo to the ArbotiX controller. I know for a fact that the servo has ID 1 because I have written an Arduino sketch that instructs servo 1 to move, and indeed it does. The servo does not respond to instructions to move servo 2, so I'm sure it's not on the broadcast ID `254`.

This should mean that we should be able to read from the MX-28. However, PyPose Terminal completely fails to find my servo:

```
PyPose starting... 
Opening port: /dev/tty.usbserial-A900gcof
Fail Read
Read Failed: Servo ID = 1
Fail Read
Read Failed: Servo ID = 2
Fail Read
Read Failed: Servo ID = 3
Fail Read
Read Failed: Servo ID = 4
Fail Read
Read Failed: Servo ID = 5
Fail Read
Read Failed: Servo ID = 6
Fail Read
Read Failed: Servo ID = 7
Fail Read
Read Failed: Servo ID = 8
Fail Read
Read Failed: Servo ID = 9
Fail Read
Read Failed: Servo ID = 10
Fail Read
Read Failed: Servo ID = 11
Fail Read
Read Failed: Servo ID = 12
Fail Read
Read Failed: Servo ID = 13
Fail Read
Read Failed: Servo ID = 14
Fail Read
Read Failed: Servo ID = 15
Fail Read
Read Failed: Servo ID = 16
Fail Read
Read Failed: Servo ID = 17
Fail Read
Read Failed: Servo ID = 18
```

As far as I can tell, the baud rate is set correctly to 57600.

**Comment by Abduoit** [comment]
@fatuhoku did u get any solution

**Comment by mikeferguson** [comment]
Archiving shortly
