### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by richard-p** [vanadiumlabs/pypose#18]
Title.
This project needs to be updated. From my experimentation the chr() function is not working correctly in python 3, and wxpython version seems incompatible as well.

**Comment by 3wnbr1** [comment]
There is indeed a lot of work required

Feel free to checkout this fork (tested with WxWidgets 4.x and python 3.6 to 3.9)
https://github.com/robotique-ecam/pypose

**Comment by mikeferguson** [comment]
Archiving shortly
