### ISSUE TITLE
error in PyPose.py and wxpython3.0 ubuntu16.04

### ISSUE THREAD

**Issue by tomsepe** [vanadiumlabs/pypose#19]
error in pypose.py

thomas@ubuntudev:~/pypose$ python PyPose.py 
PyPose starting... 
Traceback (most recent call last):
File "PyPose.py", line 417, in <module>
frame = editor()
File "PyPose.py", line 156, in __init__elf.SetBackgroundColour(wx.NullColor)
AttributeError: 'module' object has no attribute 'NullColor'

so I changed
self.SetBackgroundColour(wx.NullColor)
to 
self.SetBackgroundColour((179,179,179))

and now it runs

**Comment by mikeferguson** [comment]
Archiving shortly
