### ISSUE TITLE
MX28T PyPose Generating NUKE

### ISSUE THREAD

**Issue by GuillaumeMorinDuponchelle** [vanadiumlabs/pypose#20]
Hello,
I work on an PhantomX Hexapod using MX28T servo.
When I generate the NUKE (informations) with the correct resolution and dimensions, the gait (lizard) generated is very erratic, can't rotate the body, and the front body is oriented on the Left Middle Leg (13,15,17).  
I also tested by changing the dimension of the lizard model.py,  but it seems there is no big improvments.
MX28T 's servos are very good but also expansive, so I don't want waste even 1 of them ^^"
So I prepared some questions.

In this file (lizard3.py) : 
**Question 1) Do I need to modify it using the hexapod measure ?**

class lizard3(dict):
    X_COXA = 50     # MM between front and back legs /2
    Y_COXA = 50     # MM between front/back legs /2

    L_COXA = 50     # MM distance from coxa servo to femur servo 
    L_FEMUR = 50    # MM distance from femur servo to tibia servo 
    L_TIBIA = 50    # MM distance from tibia servo to foot 

**Question 2) It seems that legs attribution on the code are inverted compared to the code generated. Is it correct to modify it or is it a specific setup/trick ?**

# Column 1 = Body Dimensions, need both specification of layout and data.
        self.vars_layout = [["Leg", 0, 1, 2, "leg.jpg"], ["Offsets",3,4,5,"body.jpg"], ["COG Offsets",6,7,""]]
        self.vars = { 0:["Coxa(mm)",50],1:["Femur(mm)",50],2:["Tibia(mm)",50],3:["X(mm)",50],4:["Y(mm)",50],5:["Mid-Y(mm)",50],6:["X(mm)",0],7:["Y(mm)",0] }
        
        # Column 3 = Servo Values, need both specification of layout and data. 
        self.servo_layout = ["LF Coxa","RF Coxa","LF Femur","RF Femur","LF Tibia","RF Tibia","","","LM Coxa","RM Coxa","LM Femur","RM Femur","LM Tibia","RM Tibia","","","LR Coxa","RR Coxa","LR Femur","RR Femur","LR Tibia","RR Tibia"]

        self.servos = { "RF Coxa":1, "RF Femur":3, "RF Tibia":5, "LF Coxa":2,"LF Femur": 4,"LF Tibia":6,"RR Coxa":7, "RR Femur":9, "RR Tibia":11, "LR Coxa":8, "LR Femur":10, "LR Tibia":12, "RM Coxa":13,"RM Femur":15,"RM Tibia":17,"LM Coxa":14,"LM Femur":16, "LM Tibia":18} 

**Question 3) It seems that the code is setup for AX12/AX18 servo. So same question ^^, is it correct to modify it or is it a specific setup/trick ? **

# Used to generate servo values for IK
        self.mins = [512 for i in range(3*self.legs+1)]
        self.maxs = [512 for i in range(3*self.legs+1)]
        self.resolutions = [1024 for i in range(3*self.legs+1)]
        self.neutrals = [512 for i in range(3*self.legs+1)]
        self.nextPose = [512 for i in range(3*self.legs+1)]
        self.signs = [1 for i in range(3*self.legs+1)]
        self.step = 0

Thank's you so much ! :)

Robotically,

Guillaume

**Comment by mikeferguson** [comment]
Archiving shortly
